#!/usr/bin/env bash
#Command script to setup NFS share on multiple nodes (with one node being server and remaining nodes as client) as Azure Batch multiinstance task
master_addr_port=(${AZ_BATCH_MASTER_NODE//:/ })
master_addr=${master_addr_port[0]}
mnt=$AZ_BATCH_TASK_SHARED_DIR

echo $mnt
pwd
echo $AZ_BATCH_IS_CURRENT_NODE_MASTER
echo $AZ_BATCH_TASK_SHARED_DIR 
echo $AZ_BATCH_HOST_LIST

#wget https://raw.githubusercontent.com/tanewill/foambatch/master/mpidebug-cmd
#mv mpidebug-cmd application-cmd

if $AZ_BATCH_IS_CURRENT_NODE_MASTER; then
    # is head node, will be nfs server, will download and prepare all the input data in nfs share dir
    mkdir $mnt/share
    chmod 777 -R $mnt/share
    echo "$mnt/share      10.0.0.0/24(rw,sync,no_root_squash,no_all_squash)" > /etc/exports
    systemctl restart nfs-server
    cd $mnt/share
    mkdir $mnt/share/OpenFOAM
    cd $mnt/share/OpenFOAM
    wget http://aainternalstore.blob.core.windows.net/batchstorage/OpenFOAM_CentOS7_HPC.tgz
    wget http://aainternalstore.blob.core.windows.net/batchstorage/OpenFOAM_CentOS7_HPC_libs.tgz
    tar zxf OpenFOAM_CentOS7_HPC.tgz
    tar zxf OpenFOAM_CentOS7_HPC_libs.tgz
    
    wget http://aainternalstore.blob.core.windows.net/batchstorage/airFoil.tgz
    tar xzf airFoil.tgz


else
    # all other nodes are nfs clients, will connect with nfs server on nfs share dir
    mkdir -p $mnt/share
    echo "$master_addr:$mnt/share    $mnt/share   nfs defaults 0 0::" >> /etc/fstab
    while :
    do
        echo "Looping"
        mount -a
        mountpoint -q $mnt/share
        if [ $? -eq 0 ]; then
            break
        else
            sleep 10
        fi
    done
fi
exit

