#!/usr/bin/env bash
#prepare environment variables for intel mpi and openfoam
mnt=$2

source /opt/intel/impi/5.1.3.181/bin64/mpivars.sh
export MPI_ROOT=$I_MPI_ROOT
export FOAM_INST_DIR=$mnt/share/OpenFOAM
source $FOAM_INST_DIR/OpenFOAM-2.3.x/etc/bashrc
export I_MPI_FABRICS=shm:dapl
export I_MPI_DAPL_PROVIDER=ofa-v2-ib0
export I_MPI_DYNAMIC_CONNECTION=0
export LD_LIBRARY_PATH=$FOAM_INST_DIR/intel64_lin:$LD_LIBRARY_PATH

cd $mnt/share/OpenFOAM/foamModelFiles
ls
wget $1 -O $mnt/share/OpenFOAM/foamModelFiles/runMe.sh -nv
pwd
source runMe.sh $3 $mnt > $mnt/runlog.txt


mv $mnt/share/OpenFOAM/TOKEEP/ $mnt/
#rm -rf $mnt/share/OpenFOAM
